title: Jekyll:iä käyttävä sivusto
description: Tervetuloa sivustolle!
theme: jekyll-theme-hacker

nav:
  - title: "Etusivu"
    url: /
  - title: "Viikko 1"
    url: /vko1.md
  - title: "Viikko 2"
    url: /vko2.md
  - title: "Viikko 3"
    url: /vko3.md
  - title: "Viikko 4"
    url: /vko4.md
  - title: "Viikko 5"
    url: /vko5.md
  - title: "Viikko 6"
    url: /vko6.md

footer: "© 2025 ebfs @ github – Rakennettu Jekyllillä"
